{
 "title": "Performance Flowmap",
 "tags": [
  "InfluxDB",
  "Jaeger"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bt",
    "label": "Business Transaction",
    "query": "label_values(PetClinic_response_time_count, bt)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(PetClinic_response_time_count, service)"
   },
   { "name": "jaeger_host", "query": "localhost" },
   { "name": "jaeger_port", "query": "16686" }
  ]
 },
 "panels": [
  {
   "title": "\"All Owners\" Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg. response time \"${bt}\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"diff\") FROM \"bt_times\" WHERE bt='All Owners' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "upper bound (+50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*1.5 FROM \"bt_times\" WHERE bt='All Owners' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lower bound (-50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*0.5 FROM \"bt_times\" WHERE bt='All Owners' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "baseline estimate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1) FROM \"bt_times\" WHERE bt='All Owners' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "\"Owner-Details\" Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg. response time \"${bt}\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"diff\") FROM \"bt_times\" WHERE bt='Owner-Details' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "upper bound (+50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*1.5 FROM \"bt_times\" WHERE bt='Owner-Details' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lower bound (-50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*0.5 FROM \"bt_times\" WHERE bt='Owner-Details' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "baseline estimate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1) FROM \"bt_times\" WHERE bt='Owner-Details' AND $timeFilter GROUP BY time(1m), \"bt\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flowmap",
   "type": "novatec-service-dependency-graph-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(PetClinic_response_time_sum[5m])/rate(PetClinic_response_time_count[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"rt_sum\")/difference(\"c\") as \"Resp. Time\", difference(\"c\")/elapsed(\"c\",1m) as \"Rate\" from (SELECT sum(\"sum\") as \"rt_sum\", sum(\"count\") as \"c\" FROM \"PetClinic_response_time\" WHERE $timeFilter GROUP BY time(1m)) GROUP BY orig_service,service,orig_node,node,orig_application,application,bt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Performance Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(rate(PetClinic_response_time_sum[5m])/rate(PetClinic_response_time_count[5m])) by(orig_node,node,orig_service,service)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "respTime",
     "measurement": "PetClinic_response_time",
     "query": "SELECT difference(\"c\")/elapsed(\"c\",1m) as \"Rate\" from (SELECT sum(\"count\") as \"c\" FROM \"PetClinic_response_time\" WHERE $timeFilter GROUP BY time(1m)) GROUP BY orig_service,service,orig_node,node,orig_application,application,bt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(rate(PetClinic_response_time_count[5m])*60) by(orig_node,node,orig_service,service)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "legendFormat": "rate",
     "measurement": "PetClinic_response_time",
     "query": "SELECT difference(\"rt_sum\")/difference(\"c\") as \"Resp. Time\" from (SELECT sum(\"sum\") as \"rt_sum\", sum(\"count\") as \"c\" FROM \"PetClinic_response_time\" WHERE $timeFilter GROUP BY time(1m)) GROUP BY orig_service,service,orig_node,node,orig_application,application,bt",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "\"$bt\" Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "avg. response time \"${bt}\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"diff\") FROM \"bt_times\" WHERE bt=~/$bt/ AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "upper bound (+50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*1.5 FROM \"bt_times\" WHERE bt=~/$bt/ AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lower bound (-50%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1)*0.5 FROM \"bt_times\" WHERE bt=~/$bt/ AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "baseline estimate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT holt_winters_with_fit(mean(\"diff\"), 1, 1) FROM \"bt_times\" WHERE bt=~/$bt/ AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}